name: Alerta de Deploy

on:
  push:
    branches:
      - main

jobs:
  notificar:
    name: Enviar Notificacion a ntfy.sh
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Ejecutar programa Hola Mundo
        run: node index.js

      - name: Enviar notificacion a ntfy.sh
        run: |
          curl -X POST https://ntfy.sh/devops-itla \
            -H "Title: ✅ Push a main detectado" \
            -H "Priority: high" \
            -H "Tags: rocket,white_check_mark" \
            -d "🚀 Nuevo commit en el repositorio '${{ github.repository }}' por ${{ github.actor }}. Rama: ${{ github.ref_name }}. Commit: ${{ github.sha }}"
